### ISSUE TITLE
Option to not have the filename suffix

### ISSUE THREAD

**Issue by zertap** [nokonoko/Uguu#1]
^Pretty much self explanatory.
Instead of xxxxxx_filename -> xxxxxx.ext

**Comment by nokonoko** [comment]
This is in place since the user can use any custom filename rather than a randomly generated one.

**Comment by zertap** [comment]
Just to clarify, I meant that if you do not want to append neither the original filename, or a custom one. Tho you probably figured this since you re-opened the issue.

**Comment by nokonoko** [comment]
Yeah, I'll add a option for it.

**Comment by nokonoko** [comment]
There, you can now do no suffix random filename, a bit messy and double dot not working yet, will have to add that and clean up a bit.
