### ISSUE TITLE
Fix link formatting when uploading file on an instance that doesn't use a subdomain

### ISSUE THREAD

**Issue by Setup2134** [nokonoko/Uguu#106]
I am serving files off of the same domain that uguu is on, when i upload a file the link that is given after uploading the file does not work
For example https://example.com/lyOvuANh.jpg brings up 404 not found, the link that should be given when uploading a file is https://example.com/files/lyOvuANh.jpg as that one works and is how it is formatted in the example config
Is there a way that I can correct it manually? Thank you

**Comment by nokonoko** [comment]
Just set your `FILE_DOMAIN` in config.json to `example.com/files`, then Uguu will add an `/ + filename` when returning the link, thus resulting in `https://example.com/files/file.jpg`.

Specifally this will affect this line in the Upload.php Class file:
`'url'      => 'https://' . $this->Connector->CONFIG['FILE_DOMAIN'] . '/' . $this->FILE_INFO['FILENAME'],`
