### ISSUE TITLE
Download pages

### ISSUE THREAD

**Issue by phz1** [nokonoko/Uguu#19]
I thought about making download pages for every file, which simply includes a download-button, a preview for the file (mp4 or gif for example), the download button simply redirects to the full url, without any token or so

**Comment by avail** [comment]
Double the server's bandwidth? Not that hard to implement, though.

**Comment by phyze** [comment]
Well, the download pages could remove themselves, as the files do.

**Comment by avail** [comment]
If you load the download page it will load the file to preview it, and if you decide to download the file it will load the file once more.

**Comment by phyze** [comment]
That's true. What if it could get implemented into a config file, and we'd have an option for using download pages or not?

**Comment by tsudoko** [comment]
If this idea ever gets implemented, please make sure to include a way to get the direct link.

**Comment by nokonoko** [comment]
Why have thumbnails/preview and shit on something that will only be available for 24 hours?

Feel free to add it, but it will be turned of by default.

**Comment by phyze** [comment]
We also could disable the 24 hours option and just use it as a permanent site.

@tsudoko The download button should redirect to the direct link, without any session or token as I stated above.

**Comment by alucard0134** [comment]
that would nullify the point of uguu

**Comment by Kattus** [comment]
@alucard0134 Some of us change the timer to better suit our needs.

**Comment by alucard0134** [comment]
true as a clone maintainer, but we all know as a maintainer it isn't that hard to remove the temporary portion of ugui
