### ISSUE TITLE
Make Uguu less shit

### ISSUE THREAD

**Issue by avail** [nokonoko/Uguu#20]
- Use composer for packages
- Silex (?) for service managing
- Clean up current code
- Replace raintpl with twig?
- Update README.md

I'll get to doing all of this when I have some free time. Soon, hopefully.
@nokonoko if you have anything to add, just write it here and I'll look into it

**Comment by nokonoko** [comment]
Will any of these changes improve speed, make it easier to setup, easier to understand what does what and how to change it while still keeping it rather minimal?

Remember that fast and simple is the key term here.

**Comment by avail** [comment]
It would add one extra step to the setup - php composer.phar install, to install the packages.
It would allow for better download URLs, such as uguu.se/generatedfilename/originalfilename, it would make the code loads easier to understand, everything would be cleaner. 
It wouldn't change the speed by much.

**Comment by alucard0134** [comment]
i still am very against the original filename idea, still really no point to any of this for a extra step for just neatness

**Comment by avail** [comment]
@alucard0134 I know this is a over a year later, but, the originalfilename can be omitted,
i.e. the uguu.se/generatedfilename would download the original file name as well.

**Comment by k0nsl** [comment]
@avail: Hello. Did you ever pursue any of those changes/additions you listed in this issue, perhaps in the form of a fork? I would be interested to see some of these changes in Uguu as well.

**Comment by avail** [comment]
@k0nsl I had completely forgotten on this issue until now. I am currently setting a developing environment, and will actually start work on those now.

**Comment by k0nsl** [comment]
That sounds great, @avail. I have an instance of Uguu deployed but I haven't done any changes worth mentioning. Looking over the code, it could certainly need a clean-up. It's a neat little project :)

**Comment by alucard0134** [comment]
daily reminder @avail still never fixed my email password

also sounds gucci

**Comment by avail** [comment]
@alucard0134 e-email password? :o

**Comment by alucard0134** [comment]
check twitter DMs ya cuck

**Comment by avail** [comment]
I haven't got any from you /shrug - if you're talking about pomf mails, I haven't got anything to do with that. poke @nokonoko for that

**Comment by alucard0134** [comment]
god fucking shit i thought you were neko

**Comment by avail** [comment]
lMAO

**Comment by alucard0134** [comment]
;_;

**Comment by avail** [comment]
I've started work on it, btw, progress can be seen @ my fork in the 'rewrite' branch, https://github.com/avail/Uguu/commits/rewrite

**Comment by fengxiaoyue** [comment]
Is this thing still alive?

**Comment by nokonoko** [comment]
maybe

**Comment by Jeroen52** [comment]
I'm here, but I'm a hoster in this case and not a dev.

**Comment by nokonoko** [comment]
Coolio, tbh I have a much more up to date version on the actual Uguu site which includes MIME typ blocking and whatnot to avoid people to just change a .exe to .jpg and whatnot.

Ill push that version one day in the nether.
