### ISSUE TITLE
a Progress bar ?

### ISSUE THREAD

**Issue by Smallinger** [nokonoko/Uguu#21]
Hi, my upload speed is very bad. When i upload a big file can't be sure that the file is still uploading without opening my network monitor.

It would be easier if there a progress bar, too finde out how much percent are left

**Comment by tsudoko** [comment]
Chrome displays your progress in the status bar thing on the bottom, upload scripts can display progress too. Not sure about ShareX since I don't use it myself, but it should have the ability to do that as well.

**Comment by Junxx** [comment]
Hey, first thx for the answer...
i dont use chrome, and there is the problem, its only a tipp, you guys use the materializecss, and in the Android browser you have a Progressbar under the URLbar, so why not ? :D.

My problem is i need too mutch work like more then 2-3 weeks to do it my self, and the biggest problem then is that is not perfect and i think then its still buggy, so i hope that the idea is good and that anyone build it in the design.

thx for your Time :P

**Comment by alwaysontop617** [comment]
This is a great idea

**Comment by nokonoko** [comment]
Feel free to add this.
