### ISSUE TITLE
Needs an Automatic Installer and an Administration Area

### ISSUE THREAD

**Issue by alwaysontop617** [nokonoko/Uguu#24]
I'd be willing to help you created an automatic installer that will do everything. You also need an Administration Area which I would also like to help you with.

**Comment by 0x587669** [comment]
please do

**Comment by avail** [comment]
but please don't do messier code than neku

**Comment by nokonoko** [comment]
my code is mint @avail, lmao.

**Comment by avail** [comment]
your commit messages suck too, @nokonoko <3

**Comment by alwaysontop617** [comment]
@avail @nokonoko @0x587669 Great idea before I begin, Do you want to use bootstrap?

**Comment by alwaysontop617** [comment]
Also Im going to need $10 to help you. You can give me money at gogetfunding.com/evolve and I'd be glad to code you a basic install. P.S. You will need to work on styles (**seriously**)

**Comment by avail** [comment]
h o l y
s h i t

**Comment by nokonoko** [comment]
> Also Im going to need $10 to help you. You can give me money at gogetfunding.com/evolve

@alwaysontop617 lmao, fuck off.

**Comment by GandaG** [comment]
> Also Im going to need $10 to help you. You can give me money at gogetfunding.com/evolve

Someone doesn't understand what open source is

**Comment by alwaysontop617** [comment]
@GandaG @nokonoko Sorry Ill do it free!!!!!

**Comment by alwaysontop617** [comment]
https://ide.c9.io/dodiaraculus/uguu
Here is the url to my code!!

**Comment by GandaG** [comment]
I don't want to be mean, [but...](https://help.github.com/articles/creating-a-pull-request/)

**Comment by alwaysontop617** [comment]
K I cant figure it out

On Wed, Feb 17, 2016 at 1:41 PM, Daniel Nunes <notifications@github.com>
wrote:

> I don't want to be mean, but...
> <https://help.github.com/articles/creating-a-pull-request/>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nokonoko/Uguu/issues/24#issuecomment-185371040>.
>



-- 
Sincerely,
Thomas Wilbur

**Comment by GandaG** [comment]
@alwaysontop617 Just fork, clone your fork, add your code and make a pull request. I'm sorry but I doubt anyone even looked at your code, specially considering it's somewhere that requires registering.

**Comment by alwaysontop617** [comment]
Is it good?

On Thu, Feb 18, 2016 at 12:30 PM, Daniel Nunes <notifications@github.com>
wrote:

> @alwaysontop617 <https://github.com/alwaysontop617> Just fork, clone your
> fork, add your code and make a pull request. I'm sorry but I doubt anyone
> even looked at your code, specially considering it's somewhere that
> requires registering.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nokonoko/Uguu/issues/24#issuecomment-185849776>.
>



-- 
Sincerely,
Thomas Wilbur

**Comment by alwaysontop617** [comment]
HELLO

**Comment by alucard0134** [comment]
IT ISNT THAT HARD OF A CONCEPT TO MAKE A PULL REQUEST

and why are there two files with a php extension that is actually pure html .-.

**Comment by nokonoko** [comment]
> and why are there two files with a php extension that is actually pure html .-.
Which ones?

**Comment by alucard0134** [comment]
ill create a pr of his changes uno sec

**Comment by alucard0134** [comment]
close pls? @nokonoko
