### ISSUE TITLE
Check.sh not working with 1440 minutes

### ISSUE THREAD

**Issue by nokonoko** [nokonoko/Uguu#28]
The current check.sh:
`#! /bin/sh
find $(grep -oP '"CONFIG_FILES_PATH", "\K(.*)(?=")' config.php) -mtime +$(grep -oP '"CONFIG_MAX_RETENTION_TIME", "\K(.*)(?=")' config.php) -exec rm -f {} \;`

Does not seem to delete files if you set it to 1440 minutes, it doesn't throw a error, it just doesn't for now uguu.se uses the old check.sh instead:
`find /home/neku/www/files/ -mmin +1440 -exec rm -f {} \;`

**Comment by Kattus** [comment]
Just realized this wasn't working for me either, and that -mtime is for minutes, so you're setting it to delete files after 1440 days (mine was set to remove after 129600 days and it obviously wasn't deleting anything lmao)

**Comment by fitrinator** [comment]
the first thing I had to do was change -mtime to -mmin.
As for the cron job:
`0,15,30,45 * * * * cd /path/to/uguu/includes && bash check.sh`

check.sh relies on the variables in config.php which it won't get it check.sh is running on a different directory.

**Comment by illumniggati** [comment]
I've just created a pull request with the fix. The flag `-mtime' uses days as an input, not minutes. `-mmin' is the correct flag.

**Comment by nokonoko** [comment]
Should be fine now then I suppose, haven't actually tested but yeah

**Comment by k0nsl** [comment]
I couldn't get `check.sh` to work even after I corrected it. So I simply created a somewhat modified solution which works for me.

Crontab:
```
0,15,30,45 * * * * /bin/bash /home/site.tld/includes/check.sh
```

Check.sh:
```
#! /bin/sh
rm -rf /home/site.tld/public/files/.err
find /home/site.tld/public/files/* -mtime +5 -exec rm {} \;
cp -R /home/site.tld/.err /home/site.tld/public/files/.err
```

As I say, it works for me.

**Comment by nokonoko** [comment]
So we fine now?
