### ISSUE TITLE
Is there a posibility of adding accounts before people can upload?

### ISSUE THREAD

**Issue by bonzi** [nokonoko/Uguu#32]
Im looking for a solution to make my instance of Uguu have uploads identifiable to a user and so can be punnished for breaking rules of uploading, e.g. illeagl stuff.

Is there a good solution to this or am I stuck?

Thanks -
    @alfster2012

**Comment by k0nsl** [comment]
@alfster2012: you could modify/include the following solution if you need this ASAP.

See: https://github.com/fethica/PHP-Login

**Comment by alfster2012** [comment]
@k0nsl how would you implement this? I'm having to do htpassword on my nginx rules which are a pain

**Comment by avail** [comment]
basic PHP knowledge is required.

**Comment by alucard0134** [comment]
and based off your avatar i doubt you have that

**Comment by nokonoko** [comment]
This is something I could add on request but be aware it might be a while until I'll deploy due to me not having time to do shit.

**Comment by Jeroen52** [comment]
I think that adding authentication to Uguu would go against what Uguu is made for.

I'm of the opinion that Uguu's authentication-less ways of working suits me and many alike.

And I'm pretty sure that there are plenty account based file uploads out in the wild.

**Comment by nokonoko** [comment]
Well ye, but they're not Uguu :), jokes aside it could be an "addon" and actually not enabled or unpacked by default.
