### ISSUE TITLE
uguu.exe can run without python?

### ISSUE THREAD

**Issue by Lorhelei** [nokonoko/Uguu#38]
I'm trying to implement Uguu on a C# application but I can't find a way to use it from here, the problem is'nt making Uguu run into my program, but into a pc without python. I tried with the Exe that comes into "Scripts" and using cmd process, but the file doesn't upload, and the log doesn't show anything. Just sends: 

> Fatal error in launcher: Unable to create process using '"'

Sorry for asking such things, im totally new in python things and I don't understand it at all.

In resume: How do I use Uguu from a C# application?

**Comment by avail** [comment]
what are you talking about..?

**Comment by Lorhelei** [comment]
@avail I'm trying to use the api into a C# project. But I want it to run in a pc without python. So I compile it into an exe. But I can't get the exe to run properly.

**Comment by avail** [comment]
First of all, Uguu is made in php, not python - so where did you get the python dependency from??
Secondly, 'the api'? You just make a HTTP Request to `uguu.se/api.php?d=upload-tool` with the file you want to upload in the `file` request.

**Comment by Lorhelei** [comment]
@avail lol. Isn't made in php. Php is web programing used to execute simple html and other script from a server side, you don't do "programming" on php.

Second: 
_Http://en.wikipedia.org/wiki/Application_programming_interface_ 

The api is the way you can use the source code into another project... 

And last: 
_https://uguu-api.readthedocs.io/en/latest/_ 

I get it from the documentation...

But I did know that you could make a Http request to make an upload. I guess I was trying the hard way. Thanks.

**Comment by nokonoko** [comment]
Haha what the fuck am I reading, @Lorhelei if you actually look at the source on this Github you would see that there is no Python, this is the front and backend to Uguu.se, not any of the tools or other stuff. 

And as Avail said the API for Uguu.se is as follows on https://github.com/nokonoko/Uguu/blob/master/tools.txt

Honey you dumb as a rock.

**Comment by Lorhelei** [comment]
I thought I left clear I was trying to use the Python API

> https://uguu-api.readthedocs.io/en/latest/

But well... Thanks anyway. :+1:
