### ISSUE TITLE
404 on nginx with php7?

### ISSUE THREAD

**Issue by misaka00251** [nokonoko/Uguu#39]
The file DOES exist.
But nginx say it DOES NOT exist and show me 404.
Should it be the problem with php7?

**Comment by Kattus** [comment]
I run this with nginx+php7.0, you've set something up wrongly.

**Comment by misaka00251** [comment]
yeah so the default directory is "/path/to/Uguu/public/files", but it default generate link like "http://example.com/files/something_here" instead of "http://example.com/public/files/something_here"

Solved.. Dumb Question.

**Comment by avail** [comment]
your vhost is supposed to point to the public/ directory, not the source one.
