### ISSUE TITLE
Some large files (about 5GB) give an error and don't get uploaded properly and fill up /tmp

### ISSUE THREAD

**Issue by Jeroen52** [nokonoko/Uguu#42]
I wouldn't really mind if it just gave an error, but it also fills up `/tmp` which is worse.

I can't make a crontab since all files getting uploaded are temporarily saved while transferring are saved in `/tmp/phpXXXXXX`

Of course if multiple 5GB files are getting uploaded the partition will fill up quickly.

**Comment by 1265578519** [comment]
你可以挂载lvm到/根目录，这样tmp可以获取一个非常巨大的空间
[root@localhost ~]# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/VolGroup-lv_root
                       400G   27.2G  372.8G  6% /
tmpfs                 499M     0  499M   0% /dev/shm
/dev/vda1             477M   28M  425M   7% /boot
[root@localhost ~]#
