### ISSUE TITLE
api gives wrong link

### ISSUE THREAD

**Issue by MrMuttons** [nokonoko/Uguu#43]
when uploading via api, in sharex , it gives me
 /storage/files/img.png 
instead of 
/storage/public/files/img.png
The file's uploaded properly, however it gives me the wrong url for it

**Comment by avail** [comment]
your host's root is supposed to be public/, not one folder above that

**Comment by MrMuttons** [comment]
root folder of site is var/www/html

root folder of uguu is var/www/html/storage
not quite sure what you mean

**Comment by avail** [comment]
root folder of site should be /var/www/html/public

**Comment by MrMuttons** [comment]
everything uploads fine, however, when using sharex it gives 
http://site.com/storage/files/file.png
instead of 
http://site.com/storage/public/files/file.png

**Comment by avail** [comment]
the 'public' bit is never supposed to be in your url.

**Comment by MrMuttons** [comment]
when i downloax off github it hase a public/files bit

**Comment by MrMuttons** [comment]
error fixed manually
