### ISSUE TITLE
代码报错，，怎么解决

### ISSUE THREAD

**Issue by 1265578519** [nokonoko/Uguu#45]
PHP Warning: require_once(includes/config.php): failed to open stream: No such file or directory in /home/ftp/w/ww/wwwroot/index.php on line 3
PHP Fatal error: require_once(): Failed opening required 'includes/config.php' (include_path='.:/vhs/kangle/ext/tpl_php5633/lib/php') in /home/ftp/w/ww/wwwroot/index.php on line 3

**Comment by 1265578519** [comment]
HTTP ERROR 500

**Comment by 1265578519** [comment]
PHP Fatal error:  Uncaught exception 'RainTpl_NotFoundException' with message 'Template footer not found!' in /home/ftp/w/ww/wwwroot/rain/rain.tpl.class.php:271
Stack trace:
#0 /home/ftp/w/ww/wwwroot/rain/rain.tpl.class.php(164): RainTPL->check_template('footer')
#1 /home/ftp/w/ww/wwwroot/index.php(28): RainTPL->draw('footer')
#2 {main}
  thrown in /home/ftp/w/ww/wwwroot/rain/rain.tpl.class.php on line 271

**Comment by 1265578519** [comment]
PHP Warning:  include_once(/path/to/uguu/includes/core.php): failed to open stream: No such file or directory in /home/ftp/w/ww/wwwroot/api.php on line 8
PHP Warning:  include_once(): Failed opening '/path/to/uguu/includes/core.php' for inclusion (include_path='.:/vhs/kangle/ext/tpl_php5633/lib/php') in /home/ftp/w/ww/wwwroot/api.php on line 8
PHP Fatal error:  Call to undefined function save_file() in /home/ftp/w/ww/wwwroot/api.php on line 28

**Comment by 1265578519** [comment]
一堆问题，求修复。

**Comment by Jeroen52** [comment]
你好!

As the warning states, it is trying to open `/path/to/uguu/includes/core.php`.

Can you show me your `config.php`? It could be that you need to edit some variables in that file.

**Comment by 1265578519** [comment]
@Jeroen52 mv includes/config.template.php includes/config.php
我进行了一个文件重命名操作，使用了默认的config.php

`<?php
//This is the configuration file for Uguu Temp File Sharing system
define("CONFIG_ROOT_URL", "http://path.to.uguu");
//Enable this if you use a subdomain for serving uploaded files
define("CONFIG_SUBUPLOAD_URL_ENABLED", "false");
//Only define this if the above is set to true
define("CONFIG_SUBUPLOAD_URL", "http://a.uguu.se");
//Path to uploaded files
define("CONFIG_FILES_PATH", "/path/to/uguu/public/files/");
//Path to Uguu's files
define("CONFIG_ROOT_PATH", "/path/to/uguu/");
//Max retention time in minutes
define("CONFIG_MAX_RETENTION_TIME", "60");
//Max retention time as a text to be displayed
define("CONFIG_MAX_RETENTION_TEXT", "1 hour");
//Length of the random chain appended to the filename
define("CONFIG_RANDOM_LENGTH", "12");
//This is the list of blocked extensions, you can remove extensions or add to this list as you like
define ("CONFIG_BLOCKED_EXTENSIONS", serialize(array("exe", "scr", "rar", "zip", "com", "vbs", "bat", "cmd", "html", "htm", "msi", "php", "php5")));
//https://wiki.gentoo.org/wiki/Handbook to set this string correctly, or just ignore it
define("VERYLO_NG_STRING_THATDOESNTREALLYD_O_ANYTHING", "ok");`

**Comment by Jeroen52** [comment]
@1265578519 You also need to edit the file and change the values in the file to the appropriate values.

You'll need to edit at least these variables:
- CONFIG_ROOT_URL
- CONFIG_FILES_PATH
- CONFIG_ROOT_PATH

Please take a look at the instructions in the [README.md](https://github.com/nokonoko/Uguu/blob/master/README.md).


---

@1265578519 您还需要编辑文件并将文件中的值更改为适当的值。

你至少需要编辑这些变量：

CONFIG_ROOT_URL
CONFIG_FILES_PATH
CONFIG_ROOT_PATH
请查看README.md中的说明。

对不起，如果一些文字可能看起来不正确，我正在努力学习中文，但我远没有流利。 我自己来自荷兰。

**Comment by 1265578519** [comment]
@Jeroen52 我在README.md中都没有找到相关的说明，可以提供一份你的config.php参考么。

**Comment by 1265578519** [comment]
@Jeroen52 
![1](https://user-images.githubusercontent.com/6442439/37245593-6fedc2ce-24d5-11e8-8a33-0907b9fa2e8f.jpg)

**Comment by Jeroen52** [comment]
@1265578519 First you need to move includes/config.template.php to includes/config.php (`mv includes/config.template.php includes/config.php`).

Then you'll need to edit includes/config.php (`nano includes/config.php`)
You'll need to change the appropriate variables to the correct values.
Here is an example of my includes/config.php.
```php
<?php
//This is the configuration file for Uguu Temp File Sharing system
define("CONFIG_ROOT_URL", "https://cockfile.com");
//Enable this if you use a subdomain for serving uploaded files
define("CONFIG_SUBUPLOAD_URL_ENABLED", "true");
//Only define this if the above is set to true
define("CONFIG_SUBUPLOAD_URL", "https://a.cockfile.com");
//Path to uploaded files
define("CONFIG_FILES_PATH", "/cock/file/");
//Path to Uguu's files
define("CONFIG_ROOT_PATH", "/home/cockfile.com/");
//Max retention time in minutes
define("CONFIG_MAX_RETENTION_TIME", "1440");
//Max retention time as a text to be displayed
define("CONFIG_MAX_RETENTION_TEXT", "24 hours");
//Length of the random chain appended to the filename
define("CONFIG_RANDOM_LENGTH", "6");
//This is the list of blocked extensions, you can remove extensions or add to this list as you like
define ("CONFIG_BLOCKED_EXTENSIONS", serialize(array("exe", "scr", "rar", "zip", "com", "vbs", "bat", "cmd", "html", "htm", "shtml", "dhtml", "xhtml", "msi", "php", "php5")));
//https://wiki.gentoo.org/wiki/Handbook to set this string correctly, or just ignore it
define("VERYLO_NG_STRING_THATDOESNTREALLYD_O_ANYTHING", "ok");
```
---
@1265578519 首先你需要将 includes/config.template.php 移动到 includes/config.php（`mv includes/config.template.php includes/config.php`）。

然后你需要编辑 includes/config.php（`nano includes/config.php`）
您需要将适当的变量更改为正确的值。
这是我的 includes/config.php 的一个例子。
```php
<?php
//This is the configuration file for Uguu Temp File Sharing system
define("CONFIG_ROOT_URL", "https://cockfile.com");
//Enable this if you use a subdomain for serving uploaded files
define("CONFIG_SUBUPLOAD_URL_ENABLED", "true");
//Only define this if the above is set to true
define("CONFIG_SUBUPLOAD_URL", "https://a.cockfile.com");
//Path to uploaded files
define("CONFIG_FILES_PATH", "/cock/file/");
//Path to Uguu's files
define("CONFIG_ROOT_PATH", "/home/cockfile.com/");
//Max retention time in minutes
define("CONFIG_MAX_RETENTION_TIME", "1440");
//Max retention time as a text to be displayed
define("CONFIG_MAX_RETENTION_TEXT", "24 hours");
//Length of the random chain appended to the filename
define("CONFIG_RANDOM_LENGTH", "6");
//This is the list of blocked extensions, you can remove extensions or add to this list as you like
define ("CONFIG_BLOCKED_EXTENSIONS", serialize(array("exe", "scr", "rar", "zip", "com", "vbs", "bat", "cmd", "html", "htm", "shtml", "dhtml", "xhtml", "msi", "php", "php5")));
//https://wiki.gentoo.org/wiki/Handbook to set this string correctly, or just ignore it
define("VERYLO_NG_STRING_THATDOESNTREALLYD_O_ANYTHING", "ok");
```

**Comment by 1265578519** [comment]
通过测试，他已经可以运行，并且必须创建一个files文件夹与中文字符需强制勾选Generate random filename。

> <?php
> //This is the configuration file for Uguu Temp File Sharing system
> define("CONFIG_ROOT_URL", "http://test.itzmx.com/");
> //Enable this if you use a subdomain for serving uploaded files
> define("CONFIG_SUBUPLOAD_URL_ENABLED", "false");
> //Only define this if the above is set to true
> define("CONFIG_SUBUPLOAD_URL", "http://test.itzmx.com/");
> //Path to uploaded files
> define("CONFIG_FILES_PATH", "/home/ftp/t/test/wwwroot/files/");
> //Path to Uguu's files
> define("CONFIG_ROOT_PATH", "/home/ftp/t/test/wwwroot/");
> //Max retention time in minutes
> define("CONFIG_MAX_RETENTION_TIME", "60");
> //Max retention time as a text to be displayed
> define("CONFIG_MAX_RETENTION_TEXT", "1 hour");
> //Length of the random chain appended to the filename
> define("CONFIG_RANDOM_LENGTH", "12");
> //This is the list of blocked extensions, you can remove extensions or add to this list as you like
> define ("CONFIG_BLOCKED_EXTENSIONS", serialize(array("exe", "scr", "rar", "zip", "com", "vbs", "bat", "cmd", "html", "htm", "msi", "php", "php5")));
> //https://wiki.gentoo.org/wiki/Handbook to set this string correctly, or just ignore it
> define("VERYLO_NG_STRING_THATDOESNTREALLYD_O_ANYTHING", "ok");
> 

CONFIG_FILES_PATH需要设置服务器的绝对路径到files文件夹，否则会出现404，不能为其它文件夹
CONFIG_ROOT_PATH需要设置到绝对路径的wwwroot文件夹，否则会出现open_basedir 错误。
因为服务器主机的php.ini启用了open_basedir = "${doc_root}:/tmp"

如果不勾选Generate random filename会导致一些异常字符引起一个后台文件管理异常。。
![2](https://user-images.githubusercontent.com/6442439/37254832-4ebb8a9c-257e-11e8-8bb1-45b5b36c181f.png)
![111](https://user-images.githubusercontent.com/6442439/37254833-4ef15a50-257e-11e8-8c45-812554afa9f4.png)

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/37255260-ba7a0e06-2584-11e8-8f8d-147ab4854187.jpg)
客户端的话randomname=on即可。

**Comment by Jeroen52** [comment]
I'm glad that you got it in a working state, all you have to do now is modify it slightly to fit your needs.

I can't really help you with the character exceptions, I'd suggest posting a detailed report about it in English so it can be permanently resolved.

---

我很高兴你已经处于工作状态，你现在要做的只是稍微修改它以适应你的需求。

我无法真正帮助你了解字符的例外情况，我建议用英文发布详细的报告，以便能够永久解决。
