### ISSUE TITLE
apache on windows server

### ISSUE THREAD

**Issue by MrMuttons** [nokonoko/Uguu#53]
Just wondering if there's a way for me to get this working on windows as i've switched serverOS'
is there a way for me to get this back up on windows? if not, is there an alternative to this with a sharex api that i can use to replace this?

**Comment by MrMuttons** [comment]
to clearify, when uploading an image, i get error 500. and am unaware of how to fix this.

**Comment by nokonoko** [comment]
Are u running nginx?

Skickat från min iPhone

**Comment by MrMuttons** [comment]
No, apachi on windows

**Comment by nokonoko** [comment]
Then u will have to match it to the nginx conf, i cant provide a example atm cuz on phone for a week.

But start with setting the permissions correctly.

Skickat från min iPhone

**Comment by MrMuttons** [comment]
turns out i didnt change the paths in the config
