### ISSUE TITLE
Enable CORS on https://uguu.se/

### ISSUE THREAD

**Issue by butjar** [nokonoko/Uguu#55]
Did you consider enabling CORS on your publicly hosted website ? I would love to integrate it as a service in a small website I host.

**Comment by opoto** [comment]
To support CORS:

- Accept/serve OPTIONS requests
- Add following headers to all PUT/POST/GET/OPTIONS/DELETE HTTP responses:
  - Access-Control-Allow-Origin: *
  - Access-Control-Allow-Methods: PUT, POST, GET, OPTIONS, DELETE

Check this page to know more on CORS:
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
