### ISSUE TITLE
Add (.kdbx) to whitelist of file types

### ISSUE THREAD

**Issue by wolfkin** [nokonoko/Uguu#58]
The `.kdbx` extension is used by KeePass to label their database files. Completely non malicious. 

https://keepass.info/index.html

**Comment by nokonoko** [comment]
Feel free to add that to your own instance, tbh I dont think that filetype is banned on uguu.se. 

However I wouldn’t recommend uploading things related to your password safe on a public file sharing service.

Skickat från min iPhone

**Comment by wolfkin** [comment]
I have other protections built into the DB but it seems whatever the issue is it's resolved now.
