### ISSUE TITLE
File upload button doesn't appear in IE11

### ISSUE THREAD

**Issue by zpt** [nokonoko/Uguu#6]
OS: Windows 8.1 Pro x64
Browser: Internet Explorer 11.0.9600.17690

The button div (class="btn") doesn't show up at all. I can't seem to find what's wrong in the CSS.

**Comment by nokonoko** [comment]
Hmmm, @Availu any ideas?

**Comment by Availu** [comment]
![image](http://img.redrosid.pw/uninspired.png)
Works fine for me, same OS and IE build as OP :(

**Comment by nokonoko** [comment]
Works fine? The select file button is gone man ;_;

**Comment by avail** [comment]
Ohhhh. That button. Derp. Let's seeee

**Comment by avail** [comment]
https://github.com/nokonoko/Uguu/pull/9 this should fix it.

**Comment by nokonoko** [comment]
Patch merged and applied to live server, should be good to go now.

**Comment by avail** [comment]
Still doesn't work because materialized overrides my position:relative; even though it gets set *after* materialized sets it... https://github.com/nokonoko/Uguu/pull/10 should actually fix it completely

**Comment by nokonoko** [comment]
Yeah noticed, broke on all browsers, not it seems to work fine on all browsers including IE tho.

**Comment by avail** [comment]
Goodie.
