### ISSUE TITLE
Files larger than 100MB cannot be saved

### ISSUE THREAD

**Issue by parkkw472** [nokonoko/Uguu#61]
### To do : set the file to save up to 500 MB

Execution environment:
> Oracle Cloud VM Instance (2 Core 1Gb) + Storage 50GB
> Apache2 + PHP 7.2 + Certbot (for https)
> Apache2 configuration: set up as described in the README

Things I tried:
> - [x] Set `post_max_size` 500M (php.ini)
> - [x] Set `upload_max_filesize` 500M (php.ini)
> - [x] Set `max_execution_time` 300 (php.ini)
> - [x] Set `max_input_time` 300 (php.ini)
> - [x] `chown -R www-data /var/www/Uguu`

If I upload a file smaller than 100MB, it works fine, but trying to upload a file larger than 100MB displays a link to the file and appears to have been uploaded normally, but it is not actually being saved. Is there any workaround for this problem?

**Comment by nokonoko** [comment]
That's weird, have u checked if u need to change something in apache confs?

On a other note I just realized nothing is actually checking how big a file is before uploading lol, I'll add that seeing as even Pomf had it.

**Comment by parkkw472** [comment]
Yes, as I said before, I think I have done all the Apache related settings.

When I see that the file is uploaded to the end, it seems that there is a problem with storing in the server, not Apache.

The Apache log only shows that it was POSTed normally, but no other errors were logged.

**Comment by parkkw472** [comment]
Two weeks have passed since the Issue opened.
This problem is still occurring. Is there a workaround?

**Comment by espressoelf** [comment]
Works fine on my new installation. From what I see, Uguu does nothing to limit the upload-size, so it's all about your PHP configuration. What does your PHP log say? Do smaller files work?

**Comment by parkkw472** [comment]
Small files are saved normally, but large files are not saved. There is no error in the PHP log :(

**Comment by nokonoko** [comment]
Can you dump ur apache/nginx and php settings so we can take a look?

**Comment by Jeroen52** [comment]
The best way to get all this info is to post is to run `php -i` in the command line.

**Comment by parkkw472** [comment]
[apache2.conf.txt](https://github.com/nokonoko/Uguu/files/5078529/apache2.conf.txt)
[php -i.txt](https://github.com/nokonoko/Uguu/files/5078530/php.-i.txt)
[php.ini.txt](https://github.com/nokonoko/Uguu/files/5078531/php.ini.txt)

> apache2.conf : `/etc/apache2/apache2.conf`
> php.ini : `/etc/php/7.2/apache2/php.ini`
> php -i.txt : `php -i` > `php -i.txt`
