### ISSUE TITLE
paste image/more uploading options?

### ISSUE THREAD

**Issue by jithatsonei** [nokonoko/Uguu#63]
on my clone i had some wacky spaghetti javascript that when a user did ctrl+v anywhere on screen and it would detect wether its an image then pass it along to the upload handler

would be pretty cash money if we can have that since win 10 plops snips into paste (so did linux long before) as well as upload via url (possibly here, with the anonymous design of uguu it may not make sense to be stealing permanently listed files just to plop them into a temp host setting)

**Comment by nokonoko** [comment]
I'll look into the paste upload feature. Uploading from URL is something I'll probably never implement on Uguu.se due to it being very abuse prone, however might add the feature to the code so one can enable it for their own site.

**Comment by Ryanll8798** [comment]
[https://github.com/nokonoko/Uguu/issues/63#issue-781492506]() @nokonoko

**Comment by Ryanll8798** [comment]
@

**Comment by nokonoko** [comment]
Might be added in the next release as an option, it would however be abused a lot.

**Comment by nokonoko** [comment]
Might add this in the next release.

**Comment by nokonoko** [comment]
Pasting has been added, url uploading will not be added.
