### ISSUE TITLE
Email registration

### ISSUE THREAD

**Issue by Kohoshi12** [nokonoko/Uguu#64]
Maybe it's not related, but I would love to register to mail.pomf.se. When I enter the site, it ask me for my username and my password, but I don't know to get a account, it's not clear. I want to use it just to register to Fediverse sites and Torrent.

**Comment by nokonoko** [comment]
It’s not a open registration thus you are not able to make an account yourself. I sometimes announce when it’s available on Twitter. 

Please email me about these question instead of opening a issue on Uguu. :)

**Comment by Kohoshi12** [comment]
Maybe a label of "registration closed" and "open for registration" on the https://status.uguu.se/ page to be clear to new users.
