### ISSUE TITLE
Block SVG files by default

### ISSUE THREAD

**Issue by tag9724** [nokonoko/Uguu#65]
SVG files can contain and execute Javascript code ( also CSS and HTML ) opening the server to XSS attacks.

## Example of SVG file

```svg
<svg xmlns="http://www.w3.org/2000/svg">

	<foreignObject>

		<script>
			alert("JS code inside SVG file !");
		</script>

	</foreignObject>

</svg>
```

> Tested it and it worked on uguu.se -> https://a.uguu.se/lQGskjE.svg
>
> ![image](https://user-images.githubusercontent.com/1997780/117560127-5cdf1a80-b08b-11eb-8584-586fecbdde9c.png)

**Comment by nokonoko** [comment]
Thanks for bringing this to my attention, I usually block file types once people actually start abusing them but let's be proactive for once.

I'll add this to the blacklist, wondering if one can specify e.g nginx to only serve svg as an image rather than with embedded shit... Probably not.

**Comment by 0xpr03** [comment]
FYI: you can use things like https://packagist.org/packages/enshrined/svg-sanitize
Otherwise you'd have to iframe that and disable scripts in it. Though it would be nice to share SVGs with other people.

**Comment by nokonoko** [comment]
I'll look into it, I agree that being able to upload svg's would be nice.
