### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by zetok** [nokonoko/Uguu#7]
As it is currently, Uguu is a proprietary code, since that's what missing license means.
I think that it's not the desired state of things?

If you are not sure which one to pick, there's https://tldrlegal.com/

Depending on what you want, you most likely may want to pick one of "main" licenses:
* [MIT](https://tldrlegal.com/license/mit-license)
* [BSD](https://tldrlegal.com/license/bsd-3-clause-license-%28revised%29)
* [LGPL-3](https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-%28lgpl-3%29)

Or, if you want my biased opinion, just simply go with [AGPLv3](https://tldrlegal.com/license/gnu-affero-general-public-license-v3-%28agpl-3.0%29) :3

**Comment by nokonoko** [comment]
Oh I forgot to add it, should be same as Pomf which is MIT.

**Comment by zetok** [comment]
Thanks :)
