### ISSUE TITLE
S3  && PostgreSQL

### ISSUE THREAD

**Issue by AlexeiKlimenko** [nokonoko/Uguu#74]
Hello.
Unfortunately haven't found out any discussing topic, that's why posting questing as issue.
1. Is it possible to use PostgreSQL instead of sqllite?
2. Does php application support S3 bucket instead of direct access storage?

We're going to deploy UGUU into K8S.

**Comment by nokonoko** [comment]
Right now there is no support for that, but could add support for it when I get the time.

**Comment by nokonoko** [comment]
PostgreSQL support has not been added!

**Comment by nokonoko** [comment]
I'll see when I have the time to implement S3, also need to add to documentation on how to configure for Postgres, but it works! Closing this issue.

**Comment by 6guard** [comment]
Hey boss!

We need S3!
Do you have some time for that?

**Comment by nokonoko** [comment]
I could add object storage support (S3/Minio/etc) to the wishlist, I don't know when I'll implement it tho, could be in 2 days or 3 months.
