### ISSUE TITLE
[META] Site is down.

### ISSUE THREAD

**Issue by shruuub** [nokonoko/Uguu#87]
Hi,
seems like uguu.se and docs.uguu.se are down.

**Comment by nokonoko** [comment]
I'm very much aware, it's hard finding hosting when you've been kicked out from pretty much all the big ones.

It will be back up once I find a a new one.

**Comment by shruuub** [comment]
Damn, sorry for the "spam" then, that sucks. Hope you find something mate :) might be worth looking at some offers on lowendtalk if you haven't already.

**Comment by MrDisguised** [comment]
> I'm very much aware, it's hard finding hosting when you've been kicked out from pretty much all the big ones.
> 
> It will be back up once I find a a new one.

There are cheap vps servers that u can try like [vultr](https://www.vultr.com/) , [hetzner](https://www.hetzner.com/) , oracle cloud , microsoft azure etc etc ?

**Comment by shruuub** [comment]
> > I'm very much aware, it's hard finding hosting when you've been kicked out from pretty much all the big ones.
> > It will be back up once I find a a new one.
> 
> There are cheap vps servers that u can try like [vultr](https://www.vultr.com/) , [hetzner](https://www.hetzner.com/) , oracle cloud , microsoft azure etc etc ?

These ones are probably the ones he references with "the big ones". There obv are quite a lot of others, even though many ones are resellers (often of hetzner).

**Comment by nokonoko** [comment]
Correct I'm banned from all of those.

Running Uguu.se on some random cheap VPS would not fare well in terms of bandwidth and resources and would face the same problem with being shunned on the first abuse report.

I'm looking into co-locating my own hardware in the future, until then Uguu will be offline most likely.

**Comment by shruuub** [comment]
> Correct I'm banned from all of those.
> 
> Running Uguu.se on some random cheap VPS would not fare well in terms of bandwidth and resources and would face the same problem with being shunned on the first abuse report.
> 
> I'm looking into co-locating my own hardware in the future, until then Uguu will be offline most likely.

There are some hosts (like alexhost/hazi.ro) who are known for ignoring these unless coming from their countries legal institutes. Can't vouch for them obv, but I suppose with a support ticket upfront you could at least temporary get uguu up again. Your choice ofc, colocation's probably the better choice longterm.

**Comment by nokonoko** [comment]
I don't have the time nor patience to bounce around on "maybe" hosts which in most cases will just shut you down and take your money, the site will be down until I've co-located servers myself and can make sure it won't get shut down again.

I'll let you all know via Twitter when it's back up.
