### ISSUE TITLE
V1.7.6 docker deployment not adding to crontab

### ISSUE THREAD

**Issue by 7zx** [nokonoko/Uguu#88]
The current behavior does not include the addition of the expire check scripts to the crontab.

**Comment by nokonoko** [comment]
It should, since it runs this:

# Add scripts to cron
RUN echo "0,30 * * * * bash /var/www/uguu/src/static/scripts/checkfiles.sh" >> /var/spool/cron/crontabs/www-data && \
    echo "0,30 * * * * bash /var/www/uguu/src/static/scripts/checkdb.sh" >> /var/spool/cron/crontabs/www-data

But perhaps that doesn't work, I'll check when I have some time over.

**Comment by 7zx** [comment]
Nope, when i run `crontab -e`, it's empty. Please fix this when you have time.

**Comment by 7zx** [comment]
**checkfiles.sh**
```
#!/bin/sh
hours=$((XXX*60))
find /path/to/files/ -mmin +$hours -exec rm -f {} \;
```
**checkdb.sh**
```sqlite3 /path/to/db/uguu.sq3 "DELETE FROM files WHERE date <= strftime('%s', datetime('now', '-XXX hours'));"```

I believe I have identified the issue. I mistakenly assumed that the path and the hours would be automatically populated when using Docker when the config.json file was edited... However, it seems that I need to manually change the path for the database too in the checkdb.sh and the path to the files in checkfiles.sh script to resolve the problem.

**Comment by 7zx** [comment]
Where are the files located when using Docker?

**Comment by 7zx** [comment]
![image](https://github.com/nokonoko/Uguu/assets/83615960/564eb25f-f810-439a-b5ee-d8616c952278)
this showed up when i ran `make run-container`

**Comment by 7zx** [comment]
This is what's on the uguu docker container crontab:

`29 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null`

**Comment by 7zx** [comment]
![image](https://github.com/nokonoko/Uguu/assets/83615960/bcc62c1f-0487-45ea-a542-551ede20c34f)
and i realised that the path for the files is wrong, shouldn't it be `/var/www/files` ?

**Comment by 7zx** [comment]
I understand that the Dockerfile includes the following lines to add the scripts to the crontab:

```
RUN echo "0,30 * * * * bash /var/www/uguu/src/static/scripts/checkfiles.sh" >> /var/spool/cron/crontabs/www-data &&
echo "0,30 * * * * bash /var/www/uguu/src/static/scripts/checkdb.sh" >> /var/spool/cron/crontabs/www-data
```

However, it seems that these additions are not taking effect...

Additionally, when running `make run-container`, I noticed the following error message in the logs: "no crontab for root." The current crontab entry is:

```
29 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
```

**Comment by 7zx** [comment]
I also believe that the correct path for the files should be `/var/www/files` instead of `/var/www/uguu/files`. I have already submitted a pull request to address this issue, which can be found [here](https://github.com/nokonoko/Uguu/pull/90).

Could you please look into this when you have some time? This is really important for me, thanks.

**Comment by nokonoko** [comment]
Did you read thru https://github.com/nokonoko/Uguu/wiki/Deploying-Uguu-V1.7.2-on-Docker

I'll take a look at it during the week if I missed something when testing this release.

**Comment by 7zx** [comment]
Of course I did… please give it a look.

**Comment by 7zx** [comment]
This is still not fixed after a fresh Uguu docker deployment, the files still doesn’t expire.

**Comment by 7zx** [comment]
```
root@08ed2a36a247:~# crontab -l
36 0 * * * "/root/.acme.sh"/acme.sh --cron --home "/root/.acme.sh" > /dev/null
root@08ed2a36a247:~#
```

**Comment by 7zx** [comment]
outdated.
