### ISSUE TITLE
File upload progress loading bar isn't working correctly

### ISSUE THREAD

**Issue by zooool** [nokonoko/Uguu#93]
When I select a file the upload progress loading bar is stuck on 0% and after waiting a while it instantly jumps to 100% and spits out the file URL. I have JavaScript enabled. I've tried both Chrome and Firefox but the result is the same.

I've noticed this happening on other instances too. Is this a bug?

**Comment by nokonoko** [comment]
Hi!

Thank you for reporting this, the issue has been solved in the V1.8.0 release.
