### ISSUE TITLE
Throws an error when uploading with no JS in Tor Browser

### ISSUE THREAD

**Issue by zooool** [nokonoko/Uguu#94]
Step 1: turn on Safest mode in Tor Browser which disables JavaScript.
Step 2: choose a file and hit Submit.
Step 3: /upload.php?output=html is loaded and an error is shown: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data.

**Comment by nokonoko** [comment]
Uguu requires JS to upload, so working as intended.
